/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    players: Player;
    coaches: Coach;
    colleges: College;
    'coach-player-notes': CoachPlayerNote;
    'saved-players': SavedPlayer;
    tournaments: Tournament;
    prospects: Prospect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    colleges: CollegesSelect<false> | CollegesSelect<true>;
    'coach-player-notes': CoachPlayerNotesSelect<false> | CoachPlayerNotesSelect<true>;
    'saved-players': SavedPlayersSelect<false> | SavedPlayersSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    prospects: ProspectsSelect<false> | ProspectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  clerkId?: string | null;
  /**
   * User roles determine access levels across the platform
   */
  roles: ('admin' | 'player' | 'coach')[];
  /**
   * First name from Clerk profile
   */
  firstName?: string | null;
  /**
   * Last name from Clerk profile
   */
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * Link to the Clerk user account
   */
  user: number | User;
  firstName: string;
  lastName: string;
  /**
   * High school graduation year
   */
  graduationYear: number;
  city?: string | null;
  state?: string | null;
  highSchool: string;
  /**
   * e.g., "5'10"
   */
  height?: string | null;
  weightedGpa?: number | null;
  unweightedGpa?: number | null;
  primaryPosition: 'point-guard' | 'shooting-guard' | 'small-forward' | 'power-forward' | 'center';
  secondaryPosition?: ('point-guard' | 'shooting-guard' | 'small-forward' | 'power-forward' | 'center') | null;
  /**
   * Tell coaches about yourself, your playing style, and goals
   */
  bio?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * URL to highlight video (YouTube, Hudl, etc.)
   */
  highlightVideo?: string | null;
  /**
   * Select tournaments you will be attending during exposure periods
   */
  tournamentSchedule?: (number | Tournament)[] | null;
  /**
   * Soft delete timestamp - if set, profile is archived
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tournaments for players and coaches to discover
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  /**
   * Tournament name (e.g., "Nike Elite Youth Basketball League")
   */
  name: string;
  /**
   * City and State (e.g., "Las Vegas, NV")
   */
  location: string;
  startDate: string;
  endDate: string;
  /**
   * Additional details about the tournament
   */
  description?: string | null;
  /**
   * Tournament website URL
   */
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  /**
   * Link to the Clerk user account
   */
  user: number | User;
  name: string;
  /**
   * Link to college/university from database
   */
  college?: (number | null) | College;
  /**
   * University name (use this if college not in database)
   */
  university: string;
  /**
   * e.g., "Women's Basketball"
   */
  programName?: string | null;
  /**
   * e.g., "Head Coach", "Assistant Coach", "Recruiting Coordinator"
   */
  position?: string | null;
  division?: ('d1' | 'd2' | 'd3' | 'naia' | 'juco' | 'other') | null;
  state?: string | null;
  region?:
    | (
        | 'new-england'
        | 'mid-atlantic'
        | 'southeast'
        | 'southwest'
        | 'midwest'
        | 'mountain-west'
        | 'west-coast'
        | 'pacific-northwest'
      )
    | null;
  email?: string | null;
  phone?: string | null;
  bio?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Soft delete timestamp - if set, profile is archived
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the database of colleges and universities for typeahead/autocomplete
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges".
 */
export interface College {
  id: number;
  school: string;
  city: string;
  state: string;
  type: 'public' | 'private';
  conference: string;
  division: 'd1' | 'd2' | 'd3' | 'naia' | 'juco' | 'other';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-player-notes".
 */
export interface CoachPlayerNote {
  id: number;
  /**
   * The coach who owns these notes
   */
  coach: number | Coach;
  /**
   * The player these notes are about
   */
  player: number | Player;
  /**
   * General notes and observations about the player
   */
  notes?: string | null;
  /**
   * History of outreach and communication with the player
   */
  contactRecords?:
    | {
        /**
         * Date of contact
         */
        date: string;
        contactType: 'email' | 'phone' | 'text' | 'in-person' | 'video' | 'game-visit' | 'campus-visit' | 'other';
        /**
         * Summary of the conversation or interaction
         */
        summary: string;
        /**
         * Does this require follow-up?
         */
        followUpNeeded?: boolean | null;
        /**
         * When to follow up
         */
        followUpDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current interest level in this player
   */
  interestLevel?: ('high' | 'medium' | 'low' | 'watching' | 'not-interested') | null;
  /**
   * Custom tags for organization
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-players".
 */
export interface SavedPlayer {
  id: number;
  /**
   * The coach who saved this player
   */
  coach: number | Coach;
  /**
   * The player that was saved
   */
  player: number | Player;
  /**
   * When the player was saved
   */
  savedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects".
 */
export interface Prospect {
  id: number;
  /**
   * The coach who created this prospect entry
   */
  coach: number | Coach;
  /**
   * Full name of the prospect
   */
  name: string;
  /**
   * Jersey/uniform number
   */
  uniformNumber?: string | null;
  /**
   * High school graduation year (Class of)
   */
  graduationYear: number;
  /**
   * Height (e.g., "5'10")
   */
  height?: string | null;
  /**
   * High school name
   */
  highSchool?: string | null;
  /**
   * AAU program/club team
   */
  aauProgram?: string | null;
  /**
   * Tournaments this prospect will be attending
   */
  tournamentSchedule?: (number | Tournament)[] | null;
  /**
   * Twitter/X handle (e.g., @username)
   */
  twitterHandle?: string | null;
  /**
   * Phone number for contact
   */
  phoneNumber?: string | null;
  /**
   * Private notes about this prospect
   */
  notes?: string | null;
  /**
   * Optional: Link to registered player if they join the platform
   */
  linkedPlayer?: (number | null) | Player;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'colleges';
        value: number | College;
      } | null)
    | ({
        relationTo: 'coach-player-notes';
        value: number | CoachPlayerNote;
      } | null)
    | ({
        relationTo: 'saved-players';
        value: number | SavedPlayer;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'prospects';
        value: number | Prospect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  roles?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  lastName?: T;
  graduationYear?: T;
  city?: T;
  state?: T;
  highSchool?: T;
  height?: T;
  weightedGpa?: T;
  unweightedGpa?: T;
  primaryPosition?: T;
  secondaryPosition?: T;
  bio?: T;
  profileImage?: T;
  highlightVideo?: T;
  tournamentSchedule?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  college?: T;
  university?: T;
  programName?: T;
  position?: T;
  division?: T;
  state?: T;
  region?: T;
  email?: T;
  phone?: T;
  bio?: T;
  profileImage?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges_select".
 */
export interface CollegesSelect<T extends boolean = true> {
  school?: T;
  city?: T;
  state?: T;
  type?: T;
  conference?: T;
  division?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-player-notes_select".
 */
export interface CoachPlayerNotesSelect<T extends boolean = true> {
  coach?: T;
  player?: T;
  notes?: T;
  contactRecords?:
    | T
    | {
        date?: T;
        contactType?: T;
        summary?: T;
        followUpNeeded?: T;
        followUpDate?: T;
        id?: T;
      };
  interestLevel?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-players_select".
 */
export interface SavedPlayersSelect<T extends boolean = true> {
  coach?: T;
  player?: T;
  savedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects_select".
 */
export interface ProspectsSelect<T extends boolean = true> {
  coach?: T;
  name?: T;
  uniformNumber?: T;
  graduationYear?: T;
  height?: T;
  highSchool?: T;
  aauProgram?: T;
  tournamentSchedule?: T;
  twitterHandle?: T;
  phoneNumber?: T;
  notes?: T;
  linkedPlayer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}