/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    players: Player;
    coaches: Coach;
    colleges: College;
    'coach-player-notes': CoachPlayerNote;
    'coach-prospects': CoachProspect;
    'coach-saved-players': CoachSavedPlayer;
    'player-saved-programs': PlayerSavedProgram;
    tournaments: Tournament;
    invitations: Invitation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    colleges: CollegesSelect<false> | CollegesSelect<true>;
    'coach-player-notes': CoachPlayerNotesSelect<false> | CoachPlayerNotesSelect<true>;
    'coach-prospects': CoachProspectsSelect<false> | CoachProspectsSelect<true>;
    'coach-saved-players': CoachSavedPlayersSelect<false> | CoachSavedPlayersSelect<true>;
    'player-saved-programs': PlayerSavedProgramsSelect<false> | PlayerSavedProgramsSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Clerk ID for synced users. Null for PayloadCMS-only admin users.
   */
  clerkId?: string | null;
  /**
   * User roles determine access levels across the platform
   */
  roles: ('admin' | 'player' | 'coach')[];
  /**
   * First name
   */
  firstName: string;
  /**
   * Last name
   */
  lastName: string;
  /**
   * Stripe customer ID for subscription management
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe subscription ID for subscription management
   */
  stripeSubscriptionId?: string | null;
  /**
   * Stripe price ID for subscription management
   */
  stripePriceId?: string | null;
  /**
   * End date of the current Stripe billing period
   */
  stripeCurrentPeriodEnd?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * Link to the Clerk user account
   */
  user: number | User;
  /**
   * First name
   */
  firstName: string;
  /**
   * Last name
   */
  lastName: string;
  /**
   * Email address (denormalized from user for easier querying)
   */
  email: string;
  /**
   * High school graduation year (e.g., "2025")
   */
  graduationYear: string;
  city: string;
  state: string;
  highSchool: string;
  /**
   * Add up to 10 awards, honors, and achievements
   */
  awards?:
    | {
        title: string;
        year: string;
        /**
         * Additional details (optional)
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Height in total inches
   */
  heightInInches?: number | null;
  /**
   * Weight in pounds (lbs)
   */
  weight?: number | null;
  /**
   * Unweighted GPA
   */
  unweightedGpa?: number | null;
  /**
   * Weighted GPA
   */
  weightedGpa?: number | null;
  /**
   * Potential areas of study
   */
  potentialAreasOfStudy?:
    | (
        | 'undecided'
        | 'stem'
        | 'business-professional'
        | 'arts-humanities'
        | 'social-science-education'
        | 'health-medicine'
        | 'public-service-law'
        | 'other'
      )[]
    | null;
  primaryPosition?: ('point-guard' | 'combo-guard' | 'wing' | 'stretch-4' | 'power-4' | 'post') | null;
  secondaryPosition?: ('point-guard' | 'combo-guard' | 'wing' | 'stretch-4' | 'power-4' | 'post') | null;
  /**
   * Tell coaches about yourself, your playing style, and goals
   */
  bio?: string | null;
  /**
   * AAU Program name
   */
  aauProgramName?: string | null;
  /**
   * AAU Team name
   */
  aauTeamName?: string | null;
  /**
   * AAU Circuit/League
   */
  aauCircuit?:
    | (
        | 'adidas-3ssb'
        | 'adidas-gold'
        | 'crossroads'
        | 'elite-40'
        | 'hoop-group'
        | 'hype-her-hoops'
        | 'insider-exposure'
        | 'new-balance-lady-e32'
        | 'new-balance-lady-p32'
        | 'nike-ecyl'
        | 'nike-eybl'
        | 'power24'
        | 'prep-girls-hoops'
        | 'puma-nxt-league'
        | 'puma-nxtpro-16'
        | 'select-40'
        | 'ua-rise'
        | 'uaa'
        | 'independent'
        | 'other'
      )
    | null;
  /**
   * AAU Coach name
   */
  aauCoach?: string | null;
  /**
   * Contact phone number
   */
  phoneNumber?: string | null;
  /**
   * X handle
   */
  xHandle?: string | null;
  /**
   * Instagram handle
   */
  instaHandle?: string | null;
  /**
   * TikTok handle
   */
  tiktokHandle?: string | null;
  /**
   * NCAA Eligibility Center ID
   */
  ncaaId?: string | null;
  /**
   * URL to profile image (uploaded via blob storage)
   */
  profileImageUrl?: string | null;
  /**
   * Add up to 10 highlight video URLs (YouTube, Hudl, etc.)
   */
  highlightVideoUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Select tournaments you will be attending
   */
  tournamentSchedule?: (number | Tournament)[] | null;
  /**
   * Points per game
   */
  ppg?: number | null;
  /**
   * Rebounds per game
   */
  rpg?: number | null;
  /**
   * Assists per game
   */
  apg?: number | null;
  /**
   * Desired levels of collegiate play
   */
  desiredLevelsOfPlay?: ('any' | 'ncaa-d1' | 'ncaa-d2' | 'ncaa-d3' | 'naia' | 'uscaa' | 'nccaa' | 'juco')[] | null;
  /**
   * Desired geographic areas
   */
  desiredGeographicAreas?:
    | (
        | 'anywhere'
        | 'northeast'
        | 'mid-atlantic'
        | 'deep-south'
        | 'midwest'
        | 'south'
        | 'rocky-mountain'
        | 'west-coast'
        | 'pacific-northwest'
        | 'other'
      )[]
    | null;
  /**
   * Desired distance from home
   */
  desiredDistanceFromHome?: ('anywhere' | 'less-than-2' | 'less-than-4' | 'less-than-8') | null;
  /**
   * Interested in Military Academies
   */
  interestedInMilitaryAcademies?: boolean | null;
  /**
   * Interested in Ultra High Academics
   */
  interestedInUltraHighAcademics?: boolean | null;
  /**
   * Interested in Faith-Based institutions
   */
  interestedInFaithBased?: boolean | null;
  /**
   * Interested in All Girls schools
   */
  interestedInAllGirls?: boolean | null;
  /**
   * Interested in HBCUs
   */
  interestedInHBCU?: boolean | null;
  /**
   * Is this player profile active?
   */
  isActive?: boolean | null;
  /**
   * Has the player committed to a school?
   */
  isCommitted?: boolean | null;
  /**
   * School the player has committed to (if applicable)
   */
  committedWhere?: string | null;
  /**
   * Soft delete timestamp - if set, profile is archived
   */
  deletedAt?: string | null;
  /**
   * Tracks which onboarding steps have been completed (1-4)
   */
  completedSteps?:
    | {
        step: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tournaments for players and coaches to discover
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  /**
   * Tournament name (e.g., "Nike Elite Youth Basketball League")
   */
  name: string;
  /**
   * Tournament City (e.g., "Las Vegas")
   */
  city: string;
  /**
   * Tournament State (e.g., "NV")
   */
  state: string;
  startDate: string;
  endDate: string;
  /**
   * Additional details about the tournament
   */
  description?: string | null;
  /**
   * Tournament website URL
   */
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  /**
   * Link to the Clerk user account
   */
  user: number | User;
  /**
   * First name
   */
  firstName: string;
  /**
   * Last name
   */
  lastName: string;
  /**
   * Email address (denormalized from user for easier querying)
   */
  email: string;
  /**
   * College ID from database
   */
  collegeId: number;
  /**
   * College name (denormalized for quick display)
   */
  collegeName: string;
  /**
   * City where the college is located
   */
  city: string;
  /**
   * State where the college is located
   */
  state: string;
  /**
   * Your coaching position
   */
  jobTitle:
    | 'head-coach'
    | 'associate-head-coach'
    | 'assistant-coach'
    | 'director-of-recruiting'
    | 'recruiting-coordinator'
    | 'director-of-operations'
    | 'director-of-player-development'
    | 'assistant-director-of-player-personnel'
    | 'graduate-assistant'
    | 'other';
  phone?: string | null;
  bio?: string | null;
  profileImageUrl?: string | null;
  /**
   * Select tournaments you will be attending
   */
  tournamentSchedule?: (number | Tournament)[] | null;
  /**
   * Soft delete timestamp - if set, profile is archived
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the database of colleges and universities for typeahead/autocomplete
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges".
 */
export interface College {
  id: number;
  school: string;
  city: string;
  state: string;
  type: 'public' | 'private';
  conference: string;
  division: 'd1' | 'd2' | 'd3' | 'naia' | 'juco' | 'other';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-player-notes".
 */
export interface CoachPlayerNote {
  id: number;
  /**
   * The coach who owns these notes
   */
  coach: number | Coach;
  /**
   * The player these notes are about
   */
  player: number | Player;
  /**
   * General notes and observations about the player
   */
  notes?: string | null;
  /**
   * History of outreach and communication with the player
   */
  contactRecords?:
    | {
        /**
         * Date of contact
         */
        date: string;
        contactType: 'email' | 'phone' | 'text' | 'in-person' | 'video' | 'game-visit' | 'campus-visit' | 'other';
        /**
         * Summary of the conversation or interaction
         */
        summary: string;
        /**
         * Does this require follow-up?
         */
        followUpNeeded?: boolean | null;
        /**
         * When to follow up
         */
        followUpDate?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current interest level in this player
   */
  interestLevel?: ('high' | 'medium' | 'low' | 'watching' | 'not-interested') | null;
  /**
   * Custom tags for organization
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-prospects".
 */
export interface CoachProspect {
  id: number;
  /**
   * The coach who created this prospect entry
   */
  coach: number | Coach;
  /**
   * First name of the prospect
   */
  firstName: string;
  /**
   * Last name of the prospect
   */
  lastName: string;
  /**
   * URL to profile image (uploaded via blob storage)
   */
  profileImageUrl?: string | null;
  /**
   * High school graduation year (Class of)
   */
  graduationYear?: number | null;
  /**
   * City
   */
  city?: string | null;
  /**
   * State
   */
  state?: string | null;
  /**
   * High school name
   */
  highSchool?: string | null;
  /**
   * Primary playing position
   */
  primaryPosition?: ('point-guard' | 'combo-guard' | 'wing' | 'stretch-4' | 'power-4' | 'post') | null;
  /**
   * Secondary playing position
   */
  secondaryPosition?: ('point-guard' | 'combo-guard' | 'wing' | 'stretch-4' | 'power-4' | 'post') | null;
  /**
   * Height in total inches
   */
  heightInInches?: number | null;
  /**
   * Weight in pounds (lbs)
   */
  weight?: number | null;
  /**
   * Bio/description of the prospect
   */
  bio?: string | null;
  /**
   * AAU Program name
   */
  aauProgramName?: string | null;
  /**
   * AAU Team name
   */
  aauTeamName?: string | null;
  /**
   * AAU Circuit/League
   */
  aauCircuit?:
    | (
        | 'adidas-3ssb'
        | 'adidas-gold'
        | 'crossroads'
        | 'elite-40'
        | 'hoop-group'
        | 'hype-her-hoops'
        | 'insider-exposure'
        | 'new-balance-lady-e32'
        | 'new-balance-lady-p32'
        | 'nike-ecyl'
        | 'nike-eybl'
        | 'power24'
        | 'prep-girls-hoops'
        | 'puma-nxt-league'
        | 'puma-nxtpro-16'
        | 'select-40'
        | 'ua-rise'
        | 'uaa'
        | 'independent'
        | 'other'
      )
    | null;
  /**
   * AAU Coach name
   */
  aauCoach?: string | null;
  /**
   * Points per game
   */
  ppg?: number | null;
  /**
   * Rebounds per game
   */
  rpg?: number | null;
  /**
   * Assists per game
   */
  apg?: number | null;
  /**
   * Unweighted GPA
   */
  unweightedGpa?: number | null;
  /**
   * Weighted GPA
   */
  weightedGpa?: number | null;
  /**
   * Potential areas of study
   */
  potentialAreasOfStudy?:
    | (
        | 'undecided'
        | 'stem'
        | 'business-professional'
        | 'arts-humanities'
        | 'social-science-education'
        | 'health-medicine'
        | 'public-service-law'
        | 'other'
      )[]
    | null;
  /**
   * NCAA Eligibility Center ID
   */
  ncaaId?: string | null;
  /**
   * Add up to 10 awards, honors, and achievements
   */
  awards?:
    | {
        title: string;
        year: string;
        /**
         * Additional details (optional)
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add up to 10 highlight video URLs (YouTube, Hudl, etc.)
   */
  highlightVideoUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tournaments this prospect will be attending
   */
  tournamentSchedule?: (number | Tournament)[] | null;
  /**
   * Desired levels of collegiate play
   */
  desiredLevelsOfPlay?: ('any' | 'ncaa-d1' | 'ncaa-d2' | 'ncaa-d3' | 'naia' | 'uscaa' | 'nccaa' | 'juco')[] | null;
  /**
   * Desired geographic areas
   */
  desiredGeographicAreas?:
    | (
        | 'anywhere'
        | 'northeast'
        | 'mid-atlantic'
        | 'deep-south'
        | 'midwest'
        | 'south'
        | 'rocky-mountain'
        | 'west-coast'
        | 'pacific-northwest'
        | 'other'
      )[]
    | null;
  /**
   * Desired distance from home
   */
  desiredDistanceFromHome?: ('anywhere' | 'less-than-2' | 'less-than-4' | 'less-than-8') | null;
  /**
   * Interested in Military Academies
   */
  interestedInMilitaryAcademies?: boolean | null;
  /**
   * Interested in Ultra High Academics
   */
  interestedInUltraHighAcademics?: boolean | null;
  /**
   * Interested in Faith-Based institutions
   */
  interestedInFaithBased?: boolean | null;
  /**
   * Interested in All Girls schools
   */
  interestedInAllGirls?: boolean | null;
  /**
   * Interested in HBCUs
   */
  interestedInHBCU?: boolean | null;
  /**
   * Phone number for contact
   */
  phoneNumber?: string | null;
  /**
   * X/Twitter handle
   */
  xHandle?: string | null;
  /**
   * Instagram handle
   */
  instaHandle?: string | null;
  /**
   * TikTok handle
   */
  tiktokHandle?: string | null;
  /**
   * Private notes about this prospect (only visible to you)
   */
  notes?: string | null;
  /**
   * Optional: Link to registered player if they join the platform
   */
  linkedPlayer?: (number | null) | Player;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-saved-players".
 */
export interface CoachSavedPlayer {
  id: number;
  /**
   * The coach who saved this player
   */
  coach: number | Coach;
  /**
   * The player that was saved
   */
  player: number | Player;
  /**
   * When the player was saved
   */
  savedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programs saved by players for their college search
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-saved-programs".
 */
export interface PlayerSavedProgram {
  id: number;
  /**
   * The player who saved this program
   */
  player: number | Player;
  /**
   * The college program that was saved
   */
  college: number | College;
  /**
   * Private notes about this program (only visible to the player)
   */
  notes?: string | null;
  /**
   * When this program was saved
   */
  savedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage invitation tokens for first-year-free promotions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  /**
   * Unique invitation token (auto-generated UUID)
   */
  token: string;
  /**
   * User role this invitation is for
   */
  role: 'player' | 'coach';
  /**
   * Stripe coupon code to apply (e.g., FIRST_YEAR_FREE)
   */
  promoCode: string;
  /**
   * Optional: Lock invitation to specific email address
   */
  invitedEmail?: string | null;
  /**
   * Admin who created this invitation
   */
  invitedBy: number | User;
  /**
   * Optional: Invitation expiry date (defaults to 14 days if not set)
   */
  expiresAt?: string | null;
  /**
   * When the invitation was redeemed (null if unused)
   */
  redeemedAt?: string | null;
  /**
   * User who redeemed this invitation
   */
  redeemedBy?: (number | null) | User;
  /**
   * Full invitation URL to share
   */
  invitationUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'colleges';
        value: number | College;
      } | null)
    | ({
        relationTo: 'coach-player-notes';
        value: number | CoachPlayerNote;
      } | null)
    | ({
        relationTo: 'coach-prospects';
        value: number | CoachProspect;
      } | null)
    | ({
        relationTo: 'coach-saved-players';
        value: number | CoachSavedPlayer;
      } | null)
    | ({
        relationTo: 'player-saved-programs';
        value: number | PlayerSavedProgram;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  roles?: T;
  firstName?: T;
  lastName?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  stripeCurrentPeriodEnd?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  graduationYear?: T;
  city?: T;
  state?: T;
  highSchool?: T;
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        description?: T;
        id?: T;
      };
  heightInInches?: T;
  weight?: T;
  unweightedGpa?: T;
  weightedGpa?: T;
  potentialAreasOfStudy?: T;
  primaryPosition?: T;
  secondaryPosition?: T;
  bio?: T;
  aauProgramName?: T;
  aauTeamName?: T;
  aauCircuit?: T;
  aauCoach?: T;
  phoneNumber?: T;
  xHandle?: T;
  instaHandle?: T;
  tiktokHandle?: T;
  ncaaId?: T;
  profileImageUrl?: T;
  highlightVideoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  tournamentSchedule?: T;
  ppg?: T;
  rpg?: T;
  apg?: T;
  desiredLevelsOfPlay?: T;
  desiredGeographicAreas?: T;
  desiredDistanceFromHome?: T;
  interestedInMilitaryAcademies?: T;
  interestedInUltraHighAcademics?: T;
  interestedInFaithBased?: T;
  interestedInAllGirls?: T;
  interestedInHBCU?: T;
  isActive?: T;
  isCommitted?: T;
  committedWhere?: T;
  deletedAt?: T;
  completedSteps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  user?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  collegeId?: T;
  collegeName?: T;
  city?: T;
  state?: T;
  jobTitle?: T;
  phone?: T;
  bio?: T;
  profileImageUrl?: T;
  tournamentSchedule?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colleges_select".
 */
export interface CollegesSelect<T extends boolean = true> {
  school?: T;
  city?: T;
  state?: T;
  type?: T;
  conference?: T;
  division?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-player-notes_select".
 */
export interface CoachPlayerNotesSelect<T extends boolean = true> {
  coach?: T;
  player?: T;
  notes?: T;
  contactRecords?:
    | T
    | {
        date?: T;
        contactType?: T;
        summary?: T;
        followUpNeeded?: T;
        followUpDate?: T;
        id?: T;
      };
  interestLevel?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-prospects_select".
 */
export interface CoachProspectsSelect<T extends boolean = true> {
  coach?: T;
  firstName?: T;
  lastName?: T;
  profileImageUrl?: T;
  graduationYear?: T;
  city?: T;
  state?: T;
  highSchool?: T;
  primaryPosition?: T;
  secondaryPosition?: T;
  heightInInches?: T;
  weight?: T;
  bio?: T;
  aauProgramName?: T;
  aauTeamName?: T;
  aauCircuit?: T;
  aauCoach?: T;
  ppg?: T;
  rpg?: T;
  apg?: T;
  unweightedGpa?: T;
  weightedGpa?: T;
  potentialAreasOfStudy?: T;
  ncaaId?: T;
  awards?:
    | T
    | {
        title?: T;
        year?: T;
        description?: T;
        id?: T;
      };
  highlightVideoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  tournamentSchedule?: T;
  desiredLevelsOfPlay?: T;
  desiredGeographicAreas?: T;
  desiredDistanceFromHome?: T;
  interestedInMilitaryAcademies?: T;
  interestedInUltraHighAcademics?: T;
  interestedInFaithBased?: T;
  interestedInAllGirls?: T;
  interestedInHBCU?: T;
  phoneNumber?: T;
  xHandle?: T;
  instaHandle?: T;
  tiktokHandle?: T;
  notes?: T;
  linkedPlayer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-saved-players_select".
 */
export interface CoachSavedPlayersSelect<T extends boolean = true> {
  coach?: T;
  player?: T;
  savedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-saved-programs_select".
 */
export interface PlayerSavedProgramsSelect<T extends boolean = true> {
  player?: T;
  college?: T;
  notes?: T;
  savedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  state?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  token?: T;
  role?: T;
  promoCode?: T;
  invitedEmail?: T;
  invitedBy?: T;
  expiresAt?: T;
  redeemedAt?: T;
  redeemedBy?: T;
  invitationUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}